sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  - secure: upctLPoE3V7b5XTEwCkJXCwjpqa2jJjLK9wJcl59q0069KifhL3UtuKKhKb6vpRxpktGf5FUaBLGhusZTvRg0b1sdEXpv2i/kytBukzm+4DL7Lli8wt7qsHMB8uBiG5VTgiC/JqAn3RPDVWukZgzbyrg7ESoyMd/Gh/KBTjBdd5fY3cbHMNsFecGv0/FZGnDk6hJHiCoBoZgDiU8lDuai+jP/z/tm4AGiebwX3bq4+e6pzgsXQlQlJlpI81a77KZSgRU4dSUBzmbqwOUGYgM+f2yyHHb6rbsGDGl+fi4E6MxTxGpLMSc69MkqLTJ1lZlCXVVkMRZmNAhm3cEMFDivC7++l228elnaGIgrVg/WDGYQ2GGOXq1PmDZNRASqTBToX2RjF+4MUCDP0EZylU22FnPEOJLO6gfNMHWbjvQSOH/r46npeaxkRMr3ZdkHlwklnFnZLsbmFLRDAOjzKqjxBnhmxVdUBLkLxygnycRNY4PCAXQeMDBzetsVCaXo4ncDGm8Yj5s7aApdj6CFYaUO/IJIo9F1fxsWtYiW5hH8bfktSEMLeegHhJ5eKcueYcjGIQSYXQeJKgpdF/VEbF2HARMiFbbdTRU3jCz41flJRfKGVCXcnYaMRdBERn82LnEblgAGtjZpNQ4ceO44ZVG/+6mKWXGRAg1fNm1bGkvtwM=
  - secure: u6OKoewrEySuS50XBh6a1BOiKSZ/VU2pI0qE37/EyOug6vKEdVWE0XaP+r1AjFVfWhI8KNmS4/yDvBiHn9CTrdMrhi8QABPXKQ6nTUFrCM057MzAbN8Y/jygsYy0rI2fF2YrW3/t2uHjp69vNE9shqzluNxMJdw8rZdNR9JP/KpsnxmOxtdKjzb48oKMbY+9Vvwm5hAHL1hVDAhvQRjLnjPQlMYq1dl3sGo948N/wrTE4YwAUWN97IRITHdC8bhBAz6KZ1Ubq4GKteZLhNDJjhmahY7SGhsCU29tWBqwFBAsoHyxbNXg5Rgpe8TWtol5E6wQpEK8DjGrpQjaU4i1vb3RYjJGCMyiXW2vUIi8PzBBHSG3Yp6kq04eAyD0Z9K2M6cnisg1XnVNJF8XX/mvEyj8mGq2cbPGDUrnoyIwMs43ezjNbZ6emd5rBvgpRmcIqBjEb23z702bxWhpsm9J8OV6/PIG6bf1fXlk+xZDlC0kdDpjUqSqbdGloBxUnJi8qxeusyLtAid5PA24liNa1fJ/R/2ZEVKyd+hrRT5GiL33tCb+7Zx8F0QS6ZaMBGtZWnRqVPyEhydOqC3XKJa/iyM3+muTOF58GCAnHWg/xjaNLFLY6ky70619I3Nx6IXEWNhOsr/tWwSdLoj2oXAFbhuysnMPaKPipd1ffjeP/sw=
