sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  global:
  - secure: w1Kz47bqSsy3RL8MnSudHjt76moXrklOZXK5MNQEkFvZSImQfTeTVenTbzn3XnThkp5nI5YF3xialQEzW9+q49BDBqA4J5iTl4mgv+GXeY2UmvU7US8+dX59xZuAgWRgQW0JX2ZWOpbFb35H+1vOGdPp7qNie9xqcZtvBaXLcMwKy5bXQhbAWeHk30HpRYK6a/P9QwxS4/eX6CZbEHOf3h0WeF9Fn3BL4qZC2lupvqWmonWHc6U//jyOqpeloiIzRgI6kNFWYn9Y0CJF8mW31CLJMo/rGrMJH4BBF9XAyf3iNePER2Pgx526c2txQugSvXXWpk2SgetUrfNs4rQlzjo/BSx2t6yOX0Q5LS7JkU/OmyV+/QM3rkEyTEET0umP5fUnptS3IPrl7/Grtg2nyIabgv5hU8PRND85w+FbY9X+yYmEFmSPdbR8FaDwceY4+stW2T2Ri+4rPWNZVwtzpmu/Qdn9qMLQJV+tO3mGEq1qPSyDd4E3Tn+ILj4rdo/mE3gdO+1cG2wTbOpE2ISSXIGqDx44/lheK7d6a6ZWaM+ZhSYXgc8ZVf/nDwwIya/8zjCaCXE2e4repgWKuS1CqiRhveaLvuP92JOsB0vJgwk3jZbqWsufnFabF0KzShCdUpRlOr34emYJ4PcCvB/JqX4V4YB30hMwp0cuKjbcLDo=
  - secure: ReSVIFgxhDEG9SZrt9NAmxJd8NQoHHSIaI4wUAG3ZqyN7POUf5YG8BpcUXpXW0mbcyOH031mdWVDjt1kMR1Q8WgUyPwhNK16i8FSHj3ayhEK1C5z5KAONUVbWb822mdV6HGAvkwBHr59a3/ilOHxAREeIOydFEGgXvFhoQM9mb7ZRFs8PkQSfnFo4OO9uyWl0txhvhUW4JDoDh5M4J8Pxi1DSDPWmzZcRrHuZnMzgclZcON3Coo8eE3zqruKhGtLVboDibih6T3BhxPSUcvE1Av+iweUVvKEKLaU9mYLz/YM3Crrjs7DaFARvI7hRnaaYteb1qffJI3+SxV5SR1+2pRbmIVWAIwDkj7eKGTBbQeywUg+67IYxIqirouBFP5ZcU6XvH6RVkXyFuvZl5RuBEw+cBfdZ4vCIEic2QIx3f8nO49Qya0vr0UHGhtE473A7bu9Qt1QDnK0p1DKsYvx4cS+b+Lba5QjioWfWuOFsghBNMR0wBucqQUi08CJB1X0tgVSSdPsyMS6kcuA6yWnAcRF9+oUCyzurS4HD+R6lJnGzgfsBEx42vZ5ziYiZU0fKzXuaHJEhH9+gzR8i1ehD8YEEbiYkaeMk4Nk8J+k1EmBl9d8xRPp03rjvGE3WWzeKUjFzH5K/gfwCSaZV+k3svRHqVQ4BbaGXpRg3hw9r5g=
