sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo $PASSWORD
- echo $PASSWORD | docker login -u "codingblazer" --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  secure: "S7nLTO+RTAEyhXjGN8lP5EoBhrnarN5/D8iSi3+8vkvTR8fwlLerYAolClibzhB5G4WqrFE5COrb0vL4fufMxyCWiy83xwSe+VGRtgAu80p7WkR1iyBy5n0nFNLyx/5CDHBfIwRXODdmvDdCDDUkvh4Ykv8lGo9QMElfFYBqDnZKPkQhwiBPuwCXlsnCj/axE7N58gJw7sEc4rZbTTxnDnGJkkPoumeLnneGCdkgSpy9bavTlZaQfSpUxGzvzIAZmRgZOe1IrX8WlKxTaTgSySwUM2cvE5giMjQeAlsv0UlAUBItzToTi+jmj5dxoO5l7AnuXDZmoR6n67bhBhsqHPMHsdEvxm0peLNnvry+68IK4E48fXsP/KgPSa0fPUbY5i8Ae3/uU8i/zmHBK3PVsdqEYeY4g+YlwDNX0FDBbAodsNx7V0iB5Gtt0P0sgnoPT8XL036K+3TzNVm5LZA1Au28XUrO5gV0JsgbsPLY6k/HBH9RKD2Mu8KFjcR1fUYFlREr1acOJGT3E8HVPiThRNe56X1mFzqWIZLDJSVHszSe9Zb1uyRHDSQIYxvSaXFCIrD8K0GVEZfJVlTJYvVk0M2Tc2T1ngm7Dm/N5MENXrXJu6PXtOpkHk6uOKAwHQLBzgp7XK8Y1IHPDr3A/urpVl7zTAF78ER6RfxSATHSco4="