sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo $PASSWORD | docker login -u $USERNAME --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  USERNAME: "Fvy78yJLc/ATjZzJGz0GT6zxfww1BNGGG3O7QQNWg2tOZa4NtyPZPuyTxNdAQr7yy1o2dnqFBZEr5sP/zY7XAiBf8XcrcdEic9mC/sskLIv7AzFVUqr02eNWCF33HqnH44gUUNLEFjHt3L+ILt+wMbCV2j+6pYTuGuoqOMlkfkPEyAZW6+wf6rr3BWCoNA+Pc8Og0/sn4RqDLnQQK+xuVMdl+IVPu0fGHjOGMa8HbZHFTQ4fOguFsEf5QzhRisSMw/o5PSBSr7VtzPJzCVxsGqsyPQdBhxr996AL6wZANPpW+56eNjVM+WKaU8i7QrNvkgXdMPSGPSvUlsEiosBuZyUbwZ0JvdR9mo9PJ0HlC3mG7NByn4eoLqYu1nDFTkDeLJV94MIMJRlM1348BvVhvdGvKUZK3RN3JVtF7wF69DPsGm4N6+1H19KXD7z2PxbPH9Trjg7iwCY8LRRWOsk6n8M34NzuDUfEKwNMRoWGZYmcOhFy+sHmzRw4yVpA5NrMTy/cWsOk3SmDyKDDxXpFL0W5Zs5BBOlyP6sum5AerVB5X5ZjJAiglvxDS4THdL6Z0VTBUi/wsuKGUmuJRbq9WdFSPn8HetEK2aD6Q2XsFVhC5zReoGIwxl8ILlM6tWbCbExW98WBZhglMGe/gQH93gEYbVAo0g5DIKjB629bkmo="
  PASSWORD: "wq7KQ+fiIgfuQ4OjlDnAynGs6MJNWKwFlJ/Ya8EVsMKyVwT7ZRz7Vjpxt0x8ekEHgXgt7f9YJIZMtFegdugdqIfe3NyrQrlRMgrwPxkZaMD3sErxE5utAoUy3+5Ea3Utht8h3ZNAu6FhyTR6uvsE68k+6pGlN/cRA1nRUCv2Q6y/73fnCnBfo6P2IIZ0ua/3y9R2YZLbUCiGdz2Tj1OUCGC95uOpC/0qWzPThoAkuHlFBaJNswwU5ujWGjXJQPvynbRtpTrfGtG6TBnrM+bJ1TIG7h3unuJ3wGagORrzEr3JcMHI0D33C9+La8E0+H0H8oVpSz1dJnpIpURMC31ioGdQOrFz/XLIfqwuV/UAh0f9brjfTh7X8dSsInhzahUdXoBMjbCP1pqSpvDN5rIBHJaXnrwumjXmIBn/bZ3wEX291Gtzv1vPoyZYCEUZweilPqlMfqK7yMrO3DdGt2dgABt0NawbkG8wWVRqKkucGDJWEAt5Q5BFpKjSXc/B+SjrbXcys+CdZfl+AT4HNWDycRmWe8FRzQI3fX0D5YfnKtJIDiLe1vdMYbwdOsNN1yQ0M483BWbVdQhjqm9Y05PTTDQdhtuq95U9gn2imEM2X/JE+TIU+47PGAkOQhiSoYhvuurbndUDZrsCHQLtWyASB4/07mKxtAurL8vf9E4Qs8c="
