sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo $DOCKER_USERNAME
- echo $TRAVIS_SECURE_ENV_VARS
- echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  global:
  - secure: WArws0kuNpDPFr74mivK2dwQqAMHQd+3etkun6tgrkXOcOssD+Wygwtns6y1oFKOu0mOecLNOqGgKXJcY2jW2J1aoaEBYfGI/efDgh/EbWfeOkbEuj/b8BwIRVS9+/kNIjUU8ZHUUM84NzqN1Iqv0BGWKFhn/zBPjgoL2OikRk6LbeB1JmLuMVkhs4RvUXTwJuyIf1qrxGGaoDbJwQjgxQEbHFMT+NANoaDmustW5yH6DU6ByL9uu8BHPCYJI0Crw/xKC/9q8TYJRNCxrUjSdKgoCvuyLgtE6KdhjAtiNjzDSE7bI14ij6wH2juRo7jOB+Psvb0ih8iZidNfmwfPuUiVjJ4TGhGyvPTSwT4oGjAHYV7tSApwuylh7m0NVSze6l90NXs6Jmre5mRl5WPHNwdIJed7xeB7b4Ctd/NFXToXdOOss2OZjZ+N1aoVS3vylq7RkFEtglRGhPLVAqgIOrI2CcMrHsYY18zDBIFbUlTQxpZbRKuLIk3sFFzuD+nir/ckpVDkD+/1TNmF9fD69CIEzZiDinYLBs/7hGKPcbQ2qgzGkuJZowYdyCWaFX57wPrP34PpdmG3kOjgh2DtnccXvBD6UELR7D3mWJHIJ2tdKnqIlJQQYHdL9lLM08sJcEAHDY33h/wMwabOernJ80aWNwGhk0qBj/+D2E0cDOI=
  - secure: K69G2x1bJ4VdsDlmnNcMsZWgUccN61CdQNhkrrEKaqPAwg37F5yDiAoay1cTg8gNqRPS1sanm4Nw+G9NYRTEzkKMgQw/pq7aLX9ej5KBi5WjrJwphMVVqImK7yJ85+/cAHTOHOHyKyDRYQ+MpalF/PuFMMs48stUBD6Hudp/7QciC4jJ+LiWsvYbW5DjZg7ByTN3ZzHF1iuNJLkF6y+JqA+uyusRnaIrVoZc97JIuLb36ghJbAf0WF1jQxYB/+lPR2KrL7/pUbX5F0w2fdVPleK5BIFU0tCw+Hbx9KfcL5I8mQR3NezLBD21KogUHsp/Xffl1jDhS7FEWlOVimVdS02TMbsg68JvH/p1dZtgqoltu+36JOdNf6x9+5jQ9wOutY0GAgxtvBeWJyC/jUAxWWzuz6lmGqMZRwSo2jQUyAPhwLWCa1G3P4yyHfaU9rBLYJPZ3uOHmogvI97gJFQo9jTDELcz1Si3gurAnVc+UAKTHn22woNfH83+P6npQUYmxAqpVyh5YKTOSCsTj8iJDlu64eB6Fywo7c/W5U4vUo3MY2lINhvjkC8kTs2X7fYn7uKv/VWJMRNFGc6eNwNbDi9DAU8qujoJHugvNEQuE786QRvXI/VPeclUmWS8PBid0KDW8uspyQAWV9IYrzke9yvEeZNBtXVEWPyDXHukePQ=
