sudo: required
language: scala
scala:
- 2.12.6
services:
- docker

before_install:
- docker build -t sachin/dockerimage .
- docker login -u $user -p $pass
- docker push sachin/dockerimage
- docker run -d -p sachin/dockerimage
- docker ps -a

script:
- sbt ++$TRAVIS_SCALA_VERSION test