sudo: required
language: scala
scala:
  - 2.12.6
services:
  - docker
before_install:
  - docker build -t codingblazer/dockerimage .
  - echo $BUILD_LABEL
  - echo $DOCKER_USERNAME
  - echo $TRAVIS_SECURE_ENV_VARS
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push codingblazer/dockerimage
  - docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
  - docker ps -a
env:
  global:
  - BUILD_LABEL=1.0.${TRAVIS_BUILD_NUMBER}
  - secure: EQRlyjRzvH0/WzLNRPt0bKFnsqYQYXTUjb4wPJ/uVAn7zvbsjKYtiN0SG0mSQ2Ln7M9Ew9B/eKn+BkSErpxXcj+mYiqu9Lg+/3azHGP9mZzPZKGsoDDZn1hSFsyIKj5bSWjZXYDXHkftF7LRwXGJ8FXwMRqIuWa7BNHBCx2kfoW9WbPANUcLFmBFV6zUW/AJ6PgJrb6Txe6xPJlIjWHrvKtjmLYY4pI6/UArcii9qeV0qJ0/qB2YfCWSyPSeZU51f1AE2+RImnKC3m13SsGgL3DDUbHqWz3/FdazQEaADb090XPVIZbGXyBLQ/jVXR138SI8qUi/mCgPNjMT8T3uKkdCxL7UDN0q1M1UoegV+hA6mFTExvXtuj1QgQX00OBTteTKBqZoRGfa7Kn7QJH2BOTr6mWm6hM7X7x3XRwa0/O/O1EvCqpC6BQUibvtT1mX7nzhdsF8gnmQlLj3nmfg8ZoRJ+hTd/QFOxeBJy2M9NAhjQ84CoCJQdBZBrHJ5FvT++BcCERjeR9b/6UI39cZomjzRV4KdpxMUbCQdOiRlqaO5KnwQC38kK5d4F/QRFXYu5oXnodWr+vCGknJaTmvF2OJq7yo+jm/mggJBQHOxv8+ho7TFE3estC8mm2x3hnc8up+v7/Jr7dgIjpZKBAPOI5SmxyBag/HrajRGIJj7g0=
  - secure: YAahhUIt8TIy1Io2OiAQ+SiL8dxHdip1Baj0dtMBfvsHqxN1ng1k5L6m98vCr8MIa6GNVWe6Nvtq65pQSGeG2qqsRzuQSOhGqAfvDZPmOPssXorLagCIB5rmWZSOG656eXDGZjh/4wbD614sN2HI4YHUE+rxXbSpJTyPpqJPDP5IVbMUY42M89EDO6paYM+bc8ITpQ8nEEd1qyWCAoG7VNrY1IAYZbSNkc0FEU48S5zLZ0vj6dsHbHsl0m1F23f37AFFtNmxiC6lRoULGextFvWMjvbOoAbVedXcHmXUfbwk/9Wo4m2nQYpikYK45yYMFzp8FV+knhpO/CVp5hbHiinUteWwuafHCSBjGrV/G/7n4i3daygh16TmZ0OHSzJyOWG/FjynoQeXnWZ54rBzVyXYEF2H9LO1L1cyeMG/qZHFo2oCE0JVBt/YJ6E286vbp0dOJhoziKVg4p0ITXjXi3MPARQTjez6AzF//vycU7CkM2+cBcwwKoxInfN4oNjn8lA9vFVCVQkrwkZxxLKVxb7S6EPzWvd6RWfg0GZ3NZwUZuSTdX6kIEc60PJx2Yw4/7L0BV3U3avBPMMNW8AHrVfchB9omxS9ImGfRem/TFQqyDjwRDHyJPkZn5l/O0MYTdrdupssi3FXq945+C6rGZbDI6fwR3y37OJYVOw+Ubw=
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
