sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
script:
- "./run.sh"
env:
  global:
  - secure: hdAW/MfpKQA72dG7Gljlcc4LfXUQ0eEWIx3XsvNTTD8uXECyNjhQw1z7NF3/rGkAs51jU1gw/hfT91nSkIj0E4csL05l6hjGpH0RwXslveXibYWVXZIOPRsT9xyz0YF27phlySKpbjwspvzumSsyiPIDilrthj75S3kobx6dSRde3vCr2chBFvOy4SedM4etWNefH5HFhNAI2TQcpWyAt+cmHgJ/MvGnxrFrOpfD0W3jPN4Z6wbegZpYQ4lAwueQCtesQchQ/DP3nC6sb66Ah4FG1UjVCZUx9NDK4juFNUbQU7BbShpkV1apTtRjgLsuNepwQ7Mm6AHtsr+rzj3QrGtD48M1Npmf0e3vyQhWEwy69W/VuWW2GEAqOudv63KaEN3sP2ieixiGxQXtGeHVgzeIqySdG+M3t9KGxr2JDx+RFSwoJqZiZBbVakN+7i1QE2w25dntwUzn0SUobSN2N9ThNSGs7zE0bT3sQwxMh6MSOlmtD0pl4cuIqSNrOeGGgsXZFve+pGgIjah4nI5Sz/9OZ9Zrjy0BwGqZn5IfIMfzqSo7x4unQ3Y0iQJp7/k/67sGF7N/s9JjOY3JIUtjLOSoEShF8iSLMbi0x2pWscGI6hlwtLFBw1W51/talzwOji2XRWMwGRCvOe6rnObIMeoJ+HCxS2gWitmnD4K1ARA=
  - secure: Sba+x0TERlppw/3M3PMcjbTQjEKxbv+pRmtJAGRIf9r3aMqf6wthjnvlPtVyBWFPaHgmSyJSQyHc6DxEMv6hEdBNYk74rylUT5zHrJdFTOx8DytGBGa3x8ZSIHSxdfSMxxYE8Dd9U6xeQrRa17NvIZOUhW2CdKhjDamtfl5xrzCAKyK55u5YNU7KkA06qdCdcaqcZkekw/ID4LqK4P95XFbabpK5rbUo66kFrN5XH0wS5ekOTrIwtZUlnX04FQUiWieYMyn2DKuCuGeYhkLmr6zja1Xm5nIbFu6XcR1GltX8XBw164dCxdRVKL2fo2YvnUf/8IYc+rSlS2lg1yZRiG1JbnTWm7Z7UDjIm5uIm0mgFJ1M3q6fp1txHupvq8fNqsXWTDGuQs33dJ2IErvX6Bxqv8rVPlbxEHIs0wYOFYGHcy4AWWB05H3Rsv3YmjEGkEIzOcD2txnELE4MW61wrq8AAJ1qDu1iPuhBIzyMqXCPLMRaKDR2V5N57jdV8969Ty8IF6kVKFo0R3G3pWNDwE8J9NGyt2bgDazQ7b6ZHFbVwELc6gNuHNRgCleyMVm1XK8Hm3SeFmra8HftX4H6tyl7vYscnxMbTICaE7taTwAWkrPGaA638t8JJol7Ut6jTKnknZoBva0FAVc1UO6E9zfF84rVwZC+EaLshZDQ5Ns=
