sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
script:
- "./run.sh"
env:
  global:
  - secure: Jm/uZKRJvLr983WZFLNLDfIXtkeoc2iQsbMejIIcpfYD4ozZFMBtT4LrayUrbnH16QPaUJLnKioB9Evp8uQFuOk9C+GVXDWKOsZG6v7ftq3TNsQzQeW7fMUxb6pnd2ilItAqJlkssAB6VsvmdqMUuor160r5cHL2zsuT7GerW3Vdbu/owMpTZbjA5DGV1H4PQlf0zOuoyN1yGMfZEk14Z8yApO+MJ0zq8DURrwKuK1rLjFOKL1zbbbdtxzWaybRcBT6KAi0X/1lMsqTQ4gVi9li0V9wbgl+ND1KCwAbSnj0Lt6glWBrTUVVlrZcS8VpOgOIAPbFcA1iE2n67d94e1odHwajcRHA4Hj+91iTJS3gP2iruwSD47VDvg2gTzsL1bEGEJnu096/EwL0yxg+RpNXGQCDNeg63lcvQLHvho7E63c79nlHo8Jue0XIFvvIxY/+ypdT1qJ1e9KtQbT418v38FX5GkgMeImcpwvsDwiyA57YjQbc93JlxGqQGDduY08/bjwWLTyiGz3rRSPol2R8zSPBgevcdQyEKvbhLQzxyheEV4agSzNK3j5ZVvTMgs3ogNmDeGQIYJiukQTnUtnZdOe/Ez13ulzmMrcmldRrCFRbsT/MwaOofnZ2+ze/vB0SXlzyg1XC7O9Ia1bGlTKy5Gakmgt75uBVp6REsAwU=
  - secure: I0uWMclaS0qavHLESCWeICDDPhDrfV6pqg30k8GbkNStznffUeI7zOZcGr8ltroWbigw2fvobgLQnV4BzDfNUI0BASECG6CbBmC8n1sARBuo9vSggS8vmYO63k0I7lyKxXJ3i1rn0D2nl+FXdqGUgZAcU1UwSMgrL7Ar0eeBp7RYUzPEXYW5zvtzKpqbLCh0ttt54MSOKZVS2YbteVfJcegIhbr3HP1eSe1lySfWzdW0q47PHTeP80IiIoCm9O47oJ/M8hJLTfhuhzPxEt4Bl7s10l3Tq9eWZWgCh3f35+kIDNwLA3E43xeIwf1o+9TuRRQLcio2Ur/plM67N8aOERbBdZ+iejb339p/fin9NYDj78ZLqAQuQ9HOpRxst8a8bjs0YNWRX01qyrpN2tb4zNVUzLDdE2osq3eN2A7sSCQu7BaxoDQycUPxaibb7BZi9eaDkwkJhMqBoW2KkWUyVihquVV++XtftcMsTghp4X4rAgaimymu2MoDwzZG1RZq3q3rFb1tvH48Jn9ZocGlSSG8S8PzST0kbZVODly1iay/L3EMWZ8lc7bzDvtkCR6ERV7GZLoc+KdwqrXonYhPxcOPc5rw+Gd8EKp1F/57yvMPlDDQDDGXmbxGvjhSaTw9Xu3zNXB1xjCnU/3DO5aQM6ujcts8AknnqWqVf66JT6o=
