sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
script:
- "./run.sh"
env:
  global:
  - secure: a7TX789SX1hbKQSqL+CmeFPdjqJWolkS5PYPUV7jmVnUkljVtMxft/4BRxp52vg5S2qSwRrHt5n0hdLBIGeamvRjP04omkqLgIphfcEGjGVcg0Xe2pULuB/BymsyUpFP6meFTJAW1OWtixKoIIjeoki+CA+CrgwfEzzfg0wHFi8+iVTgbp6QkXWGauIiQAS7dT7b5vJ6RAt7JhmU9Nq/qSUvHLnZS5kixILAsGmumtcFbsKAGP3b088sV6/cQMz3hwMCirf2rMjblZxXAEp535udqlYEuhGeyG3oS7dNjlcMU+IAlwLmMccbvd0g2jFOtHXAZ1fJ7LUpXAvIznaOl8eQEWuc+ZbQrdQsi4TrgzyusBwBlc6xKVjEZrz0VrsHwlMMQgGXiFhlvY1ZCOvKAB3UDFeM2sqA/7SpAmFpvL+dYUFTbveG+4ljChw84CchipeOkV0kjC4K1J7JH9Jd/NFwnx4GKd0pyawuzeyBYAl6qfLlSMxAr2TwoSmvx4BSwvXaUrEMGPjfdl5UwIP0uIt1NWFsk7wWmyfg/0STWCd5XgpKa4Bj6x7P38IWx78HaPipKSMmlYcxwZA5wXY9BRMi2+ws4iUY080A1FGnvRMWi8vLew9rRZz3BP4t6Z3AvWCYSkR73Bmvz68NRDHWSXozJjVDWN0SnD39PT2NqYI=
  - secure: NfHjd3Jx+8NdqJHRbE1uVV2m+CS4icr18G8882TX7wvaH3vp3GOI8CS50a6y/dzi6M1UiFyreWSgp6Qvx9pIzXsjTc63WV+H9WS9xwi8iUxCyf1oBYt87FxqC93yO+uk5AwuUGuCXemvYnIYhHtx1tth4au80/MYhFHNNFUgdi3qISzIRSPUmtOGuI0D7DEMAeHdQ9k+wMl9srSIKBo/H312k5QoQZFSwmSoxkAYuRrt7xNa/dw2mT+ry2tQr9CEFCMaHPW/l1cECAmFlolsqrJr5jWt1acuSulqbT5pYHUaR/dy06oheZIB2zMNMwerJ8RAow3+vo03YfSnfTnnf6Ext9pnuCG8DN6LpuM8lZIJNL/aS1FVrmk8V8w8fM4eI3MzSl9ZOSKnWqDwIvveeJdRvkaz4Cew359quViad92aEn8AJu6/WPnAD/KLQQlZhbnADkFANPpRpiXH2+qRAQcY9Ja1i+tpRMx51kdlLOKT8kwL5hJS/K3FYCPkJl6xQ/iTS+l4EUMvRzp0q9uR1CM0UVknYjdqkVt4ozAI3C4qBLfNUYsb9M5cBkyFQ1sqoRPp/GIuBZ+hAz3coLl7fuO8ZvGTPOL4HtkQ4l4nK8SRQjlsq3VvD3mdAOwJuScjoeT4c36lVSntwTb7lN6ZcP92e0fZ0xwC+W0Xco9Buso=
