sudo: required
language: scala
scala:
- 2.12.6
services:
- docker
before_install:
- docker build -t codingblazer/dockerimage .
- echo $PASSWORD | docker login -u $USERNAME --password-stdin
- docker push codingblazer/dockerimage
- docker run -d -p 127.0.0.1:80:4567 codingblazer/dockerimage
- docker ps -a
script:
- sbt ++$TRAVIS_SCALA_VERSION test
env:
  USERNAME: "TlAs0jF/v8N4gackIpbkA3xocjHCUkQqf2cVb1Q2pKawun0Mf4u291FvieQX13QTV1xfmGiELmR4SoI/mH6X+90fZjekBdvFjb/plZTufOeYD7zZKIFvGOxW+SSGaZqQWSDQCZUpnX6Ms5RrmKMK7T21ssHkFMkXCpsdJkJgz7jVt7x/Kzy+CREx3itxWlE9M/NarcxHPOchPm3j0Zy1BXhGNnIyxtYm7afnBUlft2I3VbCmV8MGUwESHjl+RCDnABs3UyEvboYy8SmDDmCehHcSBCIh/DGnFysLHdR6OgM1QBqsFLJ16FFHY1H1KsBIaRX5DTJ61MUV8oiDiqxtoEkf7aBMhSbDxdqWzxKRnUA2ktEG7qoU1hvtzIpbHngNMZyJgz4BD0OeqDlj1TSShMxSioV9DU2S1H+XsjaGxyuUK1TL4466VZKBx4VOMxZ64rsMaruE2RW6MHbHFsrAnCudinkkoazDlDmkrc+Iv4LLIUSAqw5Z9dKphXGESzwQ0QuoNz3nIkHZKTzFP1P1IDksdlFAIWjCen/I9GJGhyqlkDC02/7KsacTCFxWjdA0gEGjqP5ebtWTgyP2I31B5Sg0jG3d/tkRUiiwEZQJhZ5YFuYIkoyXTKc0m+F/gqPNJjWpVpFxojRa6i1+itPEvcKL1SQCezNnMMCw2sKsD7o="
  PASSWORD: "hdHV6RBQkwDsywmcHMN5FJ9yBowt74og9DRuZ0jzeH9JQ0XUWxyZn79M8CLKVvU3ocZCpLi6Z/nc5ugmh+Nm0B0KFuTVwq7Lw57Y+yvaCyEGrRx29mFbBAbbCjB6l8rVVagKEcdeI7N9b9Wj3pnHS5bnTzwKl+PVNt60/3dtLb2DKYO1a1tcUZlRC5byftnuscIjA11vEZ51+cQ0BOfNW6mv9y6HhANempO0PnYBpt6UD+J++KT+VHdLF5F5QiepLQ6tO+YLnfpjKovdk3zYSpty1cYzOFXMuRy+3LFOykIVnXaV2KTiER8xWD7v7XNmq6WhXij0+GJGlOMqyjoofyqZfP7tBKQFiCkaEHvSAYniiAWhoPCnKsxPUhYj+BngX1dnHpWA5FV/w6wyvm9BKLcLnXXMphKyUyKZE1iIuIwhtZEMecKjvVqE3pVywdi0Dz+SSYHkDzg0VSp0fm3ZnxXv06CQ3r165ZLi5Ufh/1jZyktlUFAyoFPcrumBr/NUUuUyf+r2/UA8W7KUhb8xjnEkd0JFTa83srOfyyhRy2K8h0FaejotKIYr1wbI7i9ycLTqrrHat9GqoB+K0JSee9N9pdLgejnCq0jnDLo2oFycT0/LvdDEKqbLn4gmyBOY7B1wVB4aBXXtz65vbjwIwh6TWJcBipWFr+NCiToFbRM="